#Auth bundle
    
usuario_registrado:
  pattern: /registrar
  defaults: { _controller: PermisoAuthBundle:Security:registrarUsuario }
  
mostrar_datos:
  pattern: /mostrarDatos
  defaults: { _controller: PermisoAuthBundle:Security:mostrarDatos }
  