#Comentado porque no es necesario.
#permiso_auth_homepage:
#    pattern:  /
#    defaults: { _controller: PermisoAuthBundle:Default:index }
    
usuario_registrado:
  pattern: /registrar
  defaults: { _controller: PermisoAuthBundle:Security:registrarUsuario }
  