security:
    encoders:
        Permiso\GestionBundle\Entity\Empleado:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
 
    role_hierarchy:
        ROLE_GESTOR: [ROLE_EMPLEADO]
 
    providers:
        user_db:
            entity: { class: Permiso\GestionBundle\Entity\Empleado, property: username }
 
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: username
                password_parameter: password
                default_target_path: /empleado/inicioAplicacion
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /empleado, roles: ROLE_EMPLEADO }
        - { path: /gestor, roles: ROLE_GESTOR }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
