permiso_gestion_homepage:
    pattern:  /vacaciones
    defaults: { _controller: PermisoGestionBundle:Default:index }
    
permiso_homepage:
    pattern:  /permiso
    defaults: { _controller: PermisoGestionBundle:Default:permiso }

index_gestor:
  pattern: /gestor
  defaults: { _controller: PermisoGestionBundle:Default:gestor }


