permiso_gestion_homepage:
    pattern:  /vacaciones
    defaults: { _controller: PermisoGestionBundle:Default:index }
    
permiso_homepage:
    pattern:  /permiso
    defaults: { _controller: PermisoGestionBundle:Default:permiso }

index_gestor:
  pattern: /gestor
  defaults: { _controller: PermisoGestionBundle:Default:gestor }

nuevas_vacaciones:
  pattern: /usuario/nuevas_vacaciones
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarVacaciones }

nuevo_permiso:
  pattern: /usuario/nuevo_permiso
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarPermiso }

