#Gestión bundle

index_gestor:
  pattern: /gestor
  defaults: { _controller: PermisoGestionBundle:Default:gestor }

nuevas_vacaciones:
  pattern: /usuario/nuevas_vacaciones
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarVacaciones }

nuevo_permiso:
  pattern: /usuario/nuevo_permiso
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarPermiso }
  
inicio_aplicacion:
  pattern: /inicioAplicacion
  defaults: { _controller: PermisoGestionBundle:Default:inicio }

