#Gestión bundle

index_gestor:
  pattern: /gestor
  defaults: { _controller: PermisoGestionBundle:Default:gestor }

nuevas_vacaciones:
  pattern: /empleado/nuevas_vacaciones
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarVacaciones }

nuevo_permiso:
  pattern: /empleado/nuevo_permiso
  defaults: { _controller: PermisoGestionBundle:Solicitud:solicitarPermiso }
  
inicio_aplicacion:
  pattern: /empleado/inicioAplicacion
  defaults: { _controller: PermisoGestionBundle:Default:inicio }
  
solicitudes_pendientes:
  pattern: /empleado/solicitudesPendientes
  defaults: { _controller: PermisoGestionBundle:Solicitud:listarSolicitudesPendientesAprobacion }

solicitudes_finalizadas:
  pattern: /empleado/solicitudesFinalizadas
  defaults: { _controller: PermisoGestionBundle:Solicitud:listarSolicitudesFinalizadas }

solicitudes_pendientes_gestion:
  pattern: /gestor/solicitudesPendientesGestion
  defaults: { _controller: PermisoGestionBundle:Solicitud:listarSolicitudesPendientesGestion }

borrar_solicitud:
  pattern: /empleado/borrarSolicitud/{tipo}/{id}
  defaults: { _controller: PermisoGestionBundle:Solicitud:borrarSolicitud }

editar_vacaciones:
  pattern: /empleado/editarVacaciones/{id}
  defaults: { _controller: PermisoGestionBundle:Solicitud:editarVacaciones }
  
editar_permiso:
  pattern: /empleado/editarPermiso/{id}
  defaults: { _controller: PermisoGestionBundle:Solicitud:editarPermiso }

mostrar_solicitud:
  pattern: /empleado/mostrarSolicitud/{tipo}/{id}
  defaults: { _controller: PermisoGestionBundle:Solicitud:mostrarSolicitud }

